### ISSUE TITLE
python train_RNet.py

### ISSUE THREAD

**Issue by codingwolfman** [AITTSMD/MTCNN-Tensorflow#103]
2018-05-04 21:08:05.479084: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_301, gradients/TopKV2_grad/stack)]]
2018-05-04 21:08:05.479159: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[Node: gradients/TopKV2_grad/Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](TopKV2/_301, gradients/TopKV2_grad/stack)]]
Traceback (most recent call last):
  File "train_RNet.py", line 28, in <module>
    train_RNet(base_dir, prefix, end_epoch, display, lr)
  File "train_RNet.py", line 17, in train_RNet
    train(net_factory, prefix, end_epoch, base_dir, display=display, base_lr=lr)
  File "/home/wzy/文档/myProjects/MTCNN-Tensorflow-master/train_models/train.py", line 191, in train
    _,_,summary = sess.run([train_op, lr_op ,summary_op], feed_dict={input_image: image_batch_array, label: label_batch_array, bbox_target: bbox_batch_array,landmark_target:landmark_batch_array})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: <exception str() failed>

**Comment by GerardLiu96** [comment]
这个bug我也遇到了，请问是如何解决的？
