### ISSUE TITLE
Getting issue while processing with "widerface" dataset using "Tensorflow"

### ISSUE THREAD

**Issue by Aswiniloukya** [AITTSMD/MTCNN-Tensorflow#16]
/home/sysadmin/anaconda2/envs/tensorflow/bin/python /home/sysadmin/loukya/LC/Tensorflow-master/train_models/train_PNet.py
['/home/sysadmin/loukya/LC/Tensorflow-master/train_models', '/home/sysadmin/loukya/LC', '/home/sysadmin/loukya/LC/Tensorflow-master', '/home/sysadmin/loukya/LC/Tensorflow-master/data', '/home/sysadmin/loukya/LC/Tensorflow-master/Detection', '/home/sysadmin/loukya/LC/Tensorflow-master/logs', '/home/sysadmin/loukya/LC/Tensorflow-master/prepare_data', '/home/sysadmin/loukya/LC/Tensorflow-master/prepare_data/WIDER_train', '/home/sysadmin/loukya/LC/Tensorflow-master/prepare_data/WIDER_train/images', '/home/sysadmin/loukya/LC/Tensorflow-master/result', '/home/sysadmin/loukya/LC/Tensorflow-master/test', '/home/sysadmin/loukya/LC/Tensorflow-master/train_models', '/home/sysadmin/anaconda2/envs/tensorflow/lib/python27.zip', '/home/sysadmin/anaconda2/envs/tensorflow/lib/python2.7', '/home/sysadmin/anaconda2/envs/tensorflow/lib/python2.7/plat-linux2', '/home/sysadmin/anaconda2/envs/tensorflow/lib/python2.7/lib-tk', '/home/sysadmin/anaconda2/envs/tensorflow/lib/python2.7/lib-old', '/home/sysadmin/anaconda2/envs/tensorflow/lib/python2.7/lib-dynload', '/home/sysadmin/anaconda2/envs/tensorflow/lib/python2.7/site-packages', '/home/sysadmin/anaconda2/envs/tensorflow/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg', '/home/sysadmin/loukya/LC/Tensorflow-master/prepare_data']
/home/sysadmin/loukya/LC_output/imglists/train_PNet_landmark.txt
('Total datasets is: ', 1250000)
/home/sysadmin/loukya/LC_output/12
(64, 48, 48, 3)
(64, 48, 48, 3)
(192, 48, 48, 3)
(64, 48, 48, 3)
(384, 48, 48, 3)
(384,)
(384, 4)
(384, 48, 48, 3)
(384, 46, 46, 10)
(384, 23, 23, 10)
(384, 21, 21, 16)
(384, 19, 19, 32)
(384, 1, 1, 2)
(384, 1, 1, 4)
(384, 1, 1, 10)
WARNING:tensorflow:From /home/sysadmin/loukya/LC/Tensorflow-master/train_models/mtcnn_model.py:154: get_regularization_losses (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.get_regularization_losses instead.
2017-10-05 17:07:23.236709: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-05 17:07:23.236755: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-05 17:07:23.236761: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-05 17:07:27.217108: W tensorflow/core/kernels/queue_base.cc:302] _0_batch/fifo_queue: Skipping cancelled dequeue attempt with queue not closed
2017-10-05 17:07:27.217148: W tensorflow/core/kernels/queue_base.cc:302] _7_batch_3/fifo_queue: Skipping cancelled dequeue attempt with queue not closed
2017-10-05 17:07:27.217162: W tensorflow/core/kernels/queue_base.cc:302] _2_batch_1/fifo_queue: Skipping cancelled dequeue attempt with queue not closed
carry out！！！
Traceback (most recent call last):
  File "/home/sysadmin/loukya/LC/Tensorflow-master/train_models/train_PNet.py", line 31, in <module>
    train_PNet(base_dir, prefix, end_epoch, display, lr)
  File "/home/sysadmin/loukya/LC/Tensorflow-master/train_models/train_PNet.py", line 17, in train_PNet
    train(net_factory,prefix, end_epoch, base_dir, display=display, base_lr=lr)
  File "/home/sysadmin/loukya/LC/Tensorflow-master/train_models/train.py", line 210, in train
    coord.join(threads)
  File "/home/sysadmin/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/sysadmin/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/home/sysadmin/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1063, in _single_operation_run
    target_list_as_strings, status, None)
  File "/home/sysadmin/anaconda2/envs/tensorflow/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/sysadmin/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/sysadmin/loukya/LC_output/12/neg_landmark.tfrecord_shuffle
     [[Node: ReaderReadV2_2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2_2, input_producer_2)]]

Process finished with exit code 1

**Comment by gnleaf** [comment]
@Aswiniloukya  10.Run gen_RNet_tfrecords.py to generate tfrecords for RNet.(you should run this script four times to generate tfrecords of neg,pos,part and landmark respectively)
