### ISSUE TITLE
Traceback (most recent call last):   File "gen_imglist_rnet.py", line 17, in <module>     with open(os.path.join(data_dir, '%s/pos_%s.txt' % (size, size)), 'r') as f: IOError: [Errno 2] No such file or directory: './24/pos_24.txt'

### ISSUE THREAD

**Issue by xungeer29** [AITTSMD/MTCNN-Tensorflow#161]
你好，我在执行第9步是出现了这个错误，请问是什么原因？

**Comment by sumsuddin** [comment]
Did you run step 7 after training `PNet`?
`$ python gen_hard_example.py`

**Comment by liuyunwww** [comment]
运行gen_hard_example.py后，在24这个文件夹下要生成4个文件夹和3个文件，其中包括pos_24.txt。

**Comment by xungeer29** [comment]
@liuyunwww 感谢回答，我确实运行gen_hard_example.py了，但是没有生成4个文件夹和3个文件，而且好像还有错误，返回信息如下：Called with argument:
Namespace(batch_size=[2048, 256, 16], epoch=[18, 14, 22], min_face=24, prefix=['../data/MTCNN_model/PNet_landmark/PNet', '../data/MTCNN_model/RNet_landmark/RNet', '../data/MTCNN_model/ONet/ONet'], shuffle=False, slide_window=False, stride=2, test_mode='RNet', thresh=[0.4, 0.05, 0.7])
('Test model: ', 'RNet')
../data/MTCNN_model/PNet_landmark/PNet-18
(1, ?, ?, 3)
(1, ?, ?, 10)
(1, ?, ?, 10)
(1, ?, ?, 16)
(1, ?, ?, 32)
(1, ?, ?, 2)
(1, ?, ?, 4)
(1, ?, ?, 10)
2018-07-25 03:00:23.857783: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-07-25 03:00:23.857815: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-07-25 03:00:23.857830: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-07-25 03:00:23.857840: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-07-25 03:00:23.857849: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-07-25 03:00:24.111345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:84:00.0
Total memory: 11.93GiB
Free memory: 7.42GiB
2018-07-25 03:00:24.111408: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2018-07-25 03:00:24.111418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2018-07-25 03:00:24.111431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:84:00.0)
../data/MTCNN_model/PNet_landmark/PNet-18
restore models' param
('==================================', 'RNet')
(256, 24, 24, 3)
(256, 22, 22, 28)
(256, 11, 11, 28)
(256, 9, 9, 48)
(256, 4, 4, 48)
(256, 3, 3, 64)
(256, 576)
(256, 128)
(256, 2)
(256, 4)
(256, 10)
2018-07-25 03:00:24.679450: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:84:00.0)
../data/MTCNN_model/RNet_landmark/RNet-14
restore models' param
2018-07-25 03:00:24.766056: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key fc1/alphas not found in checkpoint
2018-07-25 03:00:24.766676: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key fc1/alphas not found in checkpoint
	 [[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]
2018-07-25 03:00:24.766868: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key fc1/alphas not found in checkpoint
	 [[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]
2018-07-25 03:00:24.767014: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key fc1/alphas not found in checkpoint
	 [[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]
2018-07-25 03:00:24.767146: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key fc1/alphas not found in checkpoint
	 [[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]
2018-07-25 03:00:24.767242: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key fc1/alphas not found in checkpoint
	 [[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]
Traceback (most recent call last):
  File "gen_hard_example.py", line 245, in <module>
    vis=False)
  File "gen_hard_example.py", line 144, in t_net
    RNet = Detector(R_Net, 24, batch_size[1], model_path[1])
  File "../Detection/detector.py", line 25, in __init__
    saver.restore(self.sess, model_path)                        
  File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key fc1/alphas not found in checkpoint
	 [[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]
	 [[Node: save/RestoreV2_14/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_54_save/RestoreV2_14", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save/RestoreV2_13', defined at:
  File "gen_hard_example.py", line 245, in <module>
    vis=False)
  File "gen_hard_example.py", line 144, in t_net
    RNet = Detector(R_Net, 24, batch_size[1], model_path[1])
  File "../Detection/detector.py", line 17, in __init__
    saver = tf.train.Saver()
  File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key fc1/alphas not found in checkpoint
	 [[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]
	 [[Node: save/RestoreV2_14/_15 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_54_save/RestoreV2_14", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

我的执行步骤如下：
1. 运行prepare_data/gen_12net_data.py
2. 运行gen_landmark_aug_12.py
3. 运行gen_imglist_pnet.py
4. 运行gen_PNet_tfrecords.py
5. 运行train_models/train_PNet.py
6. 运行prepare_data/gen_hard_example.py
7. 运行gen_landmark_aug_24.py
8. 运行gen_imglist_rnet.py
不知道是我执行步骤错了还是数据集的放错了？请问你们的数据集存放目录是怎样的？

**Comment by xungeer29** [comment]
@sumsuddin Thank you for your answer. I have run gen_landmark_aug_24.py after train the PNet, but It doesn't create those file, and the return information is shown as 
Called with argument:
Namespace(batch_size=[2048, 256, 16], epoch=[18, 14, 22], min_face=24, prefix=['../data/MTCNN_model/PNet_landmark/PNet', '../data/MTCNN_model/RNet_landmark/RNet', '../data/MTCNN_model/ONet/ONet'], shuffle=False, slide_window=False, stride=2, test_mode='RNet', thresh=[0.4, 0.05, 0.7])
('Test model: ', 'RNet')
../data/MTCNN_model/PNet_landmark/PNet-18
(1, ?, ?, 3)
(1, ?, ?, 10)
(1, ?, ?, 10)
(1, ?, ?, 16)
(1, ?, ?, 32)
(1, ?, ?, 2)
(1, ?, ?, 4)
(1, ?, ?, 10)
2018-07-25 03:00:23.857783: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-07-25 03:00:23.857815: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-07-25 03:00:23.857830: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-07-25 03:00:23.857840: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-07-25 03:00:23.857849: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-07-25 03:00:24.111345: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties:
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:84:00.0
Total memory: 11.93GiB
Free memory: 7.42GiB
2018-07-25 03:00:24.111408: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0
2018-07-25 03:00:24.111418: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0: Y
2018-07-25 03:00:24.111431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:84:00.0)
../data/MTCNN_model/PNet_landmark/PNet-18
restore models' param
('==================================', 'RNet')
(256, 24, 24, 3)
(256, 22, 22, 28)
(256, 11, 11, 28)
(256, 9, 9, 48)
(256, 4, 4, 48)
(256, 3, 3, 64)
(256, 576)
(256, 128)
(256, 2)
(256, 4)
(256, 10)
2018-07-25 03:00:24.679450: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:84:00.0)
../data/MTCNN_model/RNet_landmark/RNet-14
restore models' param
2018-07-25 03:00:24.766056: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key fc1/alphas not found in checkpoint
2018-07-25 03:00:24.766676: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key fc1/alphas not found in checkpoint
[[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]
2018-07-25 03:00:24.766868: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key fc1/alphas not found in checkpoint
[[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]
2018-07-25 03:00:24.767014: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key fc1/alphas not found in checkpoint
[[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]
2018-07-25 03:00:24.767146: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key fc1/alphas not found in checkpoint
[[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]
2018-07-25 03:00:24.767242: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Key fc1/alphas not found in checkpoint
[[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]
Traceback (most recent call last):
File "gen_hard_example.py", line 245, in 
vis=False)
File "gen_hard_example.py", line 144, in t_net
RNet = Detector(R_Net, 24, batch_size[1], model_path[1])
File "../Detection/detector.py", line 25, in init
saver.restore(self.sess, model_path)
File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
{self.saver_def.filename_tensor_name: save_path})
File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
run_metadata_ptr)
File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
feed_dict_string, options, run_metadata)
File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
target_list, options, run_metadata)
File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key fc1/alphas not found in checkpoint
[[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]
[[Node: save/RestoreV2_14/_15 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_54_save/RestoreV2_14", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]]

Caused by op u'save/RestoreV2_13', defined at:
File "gen_hard_example.py", line 245, in 
vis=False)
File "gen_hard_example.py", line 144, in t_net
RNet = Detector(R_Net, 24, batch_size[1], model_path[1])
File "../Detection/detector.py", line 17, in init
saver = tf.train.Saver()
File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1139, in init
self.build()
File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1170, in build
restore_sequentially=self._restore_sequentially)
File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 691, in build
restore_sequentially, reshape)
File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
[spec.tensor.dtype])[0])
File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 640, in restore_v2
dtypes=dtypes, name=name)
File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
op_def=op_def)
File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
original_op=self._default_original_op, op_def=op_def)
File "/home/shentao/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in init
self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key fc1/alphas not found in checkpoint
[[Node: save/RestoreV2_13 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_13/tensor_names, save/RestoreV2_13/shape_and_slices)]]
[[Node: save/RestoreV2_14/_15 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_54_save/RestoreV2_14", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]]

I run the codes follow the steps:
1. run prepare_data/gen_12net_data.py
2. run gen_landmark_aug_12.py
3. run gen_imglist_pnet.py
4. run gen_PNet_tfrecords.py
5. run train_models/train_PNet.py
6. run prepare_data/gen_hard_example.py
7. run gen_landmark_aug_24.py
8. run gen_imglist_rnet.py

I don't know whether my run codes step is wrong or other reason.
Looking forward to your answer.

**Comment by sumsuddin** [comment]
at step 6 the default mode is `RNet`, As you only have PNet now the `RNet` is not found. That's why you are getting the error. I have created a [pull request](https://github.com/AITTSMD/MTCNN-Tensorflow/pull/166/commits/05ca22ce87658979ffbe73bda42cbe475db9d942) to resolve this. You can have a look and if you copy the code, you can just run,

`$ python gen_hard_example.py --test_mode PNet`

Or you can have a quick fix as[ here](https://github.com/AITTSMD/MTCNN-Tensorflow/issues/160),

https://github.com/AITTSMD/MTCNN-Tensorflow/blob/master/prepare_data/gen_hard_example.py
Line 215
Change ONet to RNet
then run,
`$ python gen_hard_example.py --test_mode PNet`

**Comment by xungeer29** [comment]
@sumsuddin Thanks, I have solved the problem follow your advice, and I have accomplished all training tasks, but I don't know how to use the trained model to detect face, can you teach me ? Thank you.

A novice in this field.

**Comment by sumsuddin** [comment]
@xungeer29  It's easy! Just run [this](https://github.com/AITTSMD/MTCNN-Tensorflow/blob/master/test/one_image_test.py) script named **one_image_test.py** located in test directory

`$ python one_image_test.py`
