### ISSUE TITLE
File "gen_landmark_aug_12.py", line 69, in GenerateData     assert(img is not None) AssertionError

### ISSUE THREAD

**Issue by 2006lizeyuan** [AITTSMD/MTCNN-Tensorflow#170]
I have download WIDER_train, and do the first step:run gen_12net_data.py. But when I run gen_landmark_aug_12.py, a mistake happened:
$ python gen_landmark_aug_12.py
Traceback (most recent call last):
  File "gen_landmark_aug_12.py", line 189, in <module>
    imgs,landmarks = GenerateData(train_txt, OUTPUT,net,argument=True)
  File "gen_landmark_aug_12.py", line 69, in GenerateData
    assert(img is not None)
AssertionError
Do you know how to solve it?

**Comment by 2006lizeyuan** [comment]
@AITTSMD

**Comment by AITTSMD** [comment]
@2006lizeyuan 检查图像路径，看看是否没读到图像~

**Comment by bzzhc** [comment]
@2006lizeyuan ,使用项目里的trainImageList.txt   ,斜杠问题

**Comment by louqiqi** [comment]
这个路径问题怎么解决呢啊？   trainImageList.txt 里面的路径对应的是哪个文件夹的图片？

**Comment by louqiqi** [comment]
@AITTSMD

**Comment by 2006lizeyuan** [comment]
Dear Qiqi,

这是我一年前搞的代码，有点记不清了。问题好像是，作者原文件里那个txt文件并不是训练时用的那个，要自己去网上下训练集和相关记录图片名的txt。

Best,
Li Zeyuan
1-626-321-8274

在 2019年4月9日，10:02，louqiqi <notifications@github.com> 写道：

@AITTSMD

**Comment by 474383156qq** [comment]
请问这个问题该怎么解决呢
