### ISSUE TITLE
运行train.py训练ONet，出现错误tf.errors.OutOfRangeError

### ISSUE THREAD

**Issue by liuyunwww** [AITTSMD/MTCNN-Tensorflow#175]
运行train.py训练ONet，循环617次出现错误tf.errors.OutOfRangeError
测试后发现，错误出现在读取TFRecords文件
image_batch_array, label_batch_array, bbox_batch_array,landmark_batch_array = sess.run([image_batch, label_batch, bbox_batch, landmark_batch])
上网查了一下，有可能是因为我的正样本太少（pos 1528，part 19753，neg 517384）。
https://blog.csdn.net/pkokocl/article/details/78682324
网上的解决方案提到要修改tfrecord_utils.py文件中的
filename_queue = tf.train.string_input_producer([tfr_filename], shuffle = False, num_epochs = 10)
设置num_epochs，https://www.cnblogs.com/code-wangjun/p/8824406.html
试了一下，没改对。

在train.py中，我屏蔽了以下语句
if coord.should_stop():
     break

**Comment by liuyunwww** [comment]
跳过读取617对应的记录，读取下一行记录依然出现以下问题，似乎问题与数据本身无关。

616
[<tf.Tensor 'concat/image:0' shape=(320, 48, 48, 3) dtype=float32>, <tf.Tensor '
concat/label:0' shape=(320,) dtype=float32>, <tf.Tensor 'concat/roi:0' shape=(32
0, 4) dtype=float32>, <tf.Tensor 'concat/landmark:0' shape=(320, 10) dtype=float
32>]
(320, 48, 48, 3)
(320,)
(320, 4)
(320, 10)
1.0
[-0.1   0.03 -0.02  0.31]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(320, 48, 48, 3)
(320,)
(320, 4)
(320, 10)
1.0
[-0.1   0.03 -0.02  0.31]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
617
[<tf.Tensor 'concat/image:0' shape=(320, 48, 48, 3) dtype=float32>, <tf.Tensor '
concat/label:0' shape=(320,) dtype=float32>, <tf.Tensor 'concat/roi:0' shape=(32
0, 4) dtype=float32>, <tf.Tensor 'concat/landmark:0' shape=(320, 10) dtype=float
32>]
618
[<tf.Tensor 'concat/image:0' shape=(320, 48, 48, 3) dtype=float32>, <tf.Tensor '
concat/label:0' shape=(320,) dtype=float32>, <tf.Tensor 'concat/roi:0' shape=(32
0, 4) dtype=float32>, <tf.Tensor 'concat/landmark:0' shape=(320, 10) dtype=float
32>]
Done!
Traceback (most recent call last):
  File "train_models/train_ONet.py", line 30, in <module>
    train_ONet(base_dir, prefix, end_epoch, display, lr)
  File "train_models/train_ONet.py", line 18, in train_ONet
    train(net_factory, prefix, end_epoch, base_dir, display=display, baseLr=lr,
gpus='0')
  File "E:\Software\TensorFlow\mtcnn_tf-master\train_models\train.py", line 217,
 in train
    coord.join(threads)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\trainin
g\coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\six.py", line 693, in rer
aise
    raise value
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\trainin
g\queue_runner_impl.py", line 252, in _run
    enqueue_callable()
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\
session.py", line 1249, in _single_operation_run
    self._call_tf_sessionrun(None, {}, [], target_list, None)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\
session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framewo
rk\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: truncated record at 83799
0783
         [[Node: ReaderReadV2_2 = ReaderReadV2[_device="/job:localhost/replica:0
/task:0/device:CPU:0"](TFRecordReaderV2_2, input_producer_2)]]

**Comment by dlml** [comment]
你好，我也碰到这样的问题，请问你解决了吗

**Comment by liuyunwww** [comment]
没有，我卡在这了。
这个问题我以前也提过，@AITTSMD给了回答
https://github.com/AITTSMD/MTCNN-Tensorflow/issues/131
但我没解决。

**Comment by liuyunwww** [comment]
@dlml，你用的什么数据，解决了上面的问题吗？

**Comment by liuyunwww** [comment]
在gen_ONet_tfrecords.py的run方法中注释了tfrecord_writer.close()后就没再出现这个问题了。

**Comment by wanglaotou** [comment]
![image](https://user-images.githubusercontent.com/12837585/62851961-7fa79800-bd1a-11e9-8b15-850eb30e6d28.png)
首先贴一张我修改代码后的截图。对照这train_RNet.py文件来看，可以看出train_ONet.py文件是少了些东西的，我是一步一步对照着train_RNet.py文件来改的，基本上是一样的。

**Comment by immarioo** [comment]
![image](https://user-images.githubusercontent.com/12837585/62852231-6a7f3900-bd1b-11e9-9b08-ebe67f15fe6f.png)
首先贴一张我修改代码后的截图，注意这的name有四个值，每一个值运行一次，共四次。对照这gen_RNet_tfrecords.py文件来看，可以看出gen_ONet_tfrecords.py文件是少了些东西的，我是一步一步对照着gen_RNet_tfrecords.py文件来改的，基本上流程和代码是一样的。
