### ISSUE TITLE
Onet: tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 1728 values, but the requested shape has 6912

### ISSUE THREAD

**Issue by NoahLu1105** [AITTSMD/MTCNN-Tensorflow#232]
when i run   train_ONet.py,

```
Traceback (most recent call last):
  File "train_models/train_ONet.py", line 28, in <module>
    train_ONet(base_dir, prefix, end_epoch, display, lr)
  File "train_models/train_ONet.py", line 17, in train_ONet
    train(net_factory, prefix, end_epoch, base_dir, display=display, base_lr=lr)
  File "/home/ln/code/MTCNN/git/MTCNN-Tensorflow/train_models/train.py", line 244, in train
    coord.join(threads)
  File "/home/ln/deploy/python/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/ln/deploy/python/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/home/ln/deploy/python/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1231, in _single_operation_run
    target_list_as_strings, status, None)
  File "/home/ln/deploy/python/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 1728 values, but the requested shape has 6912
         [[Node: Reshape_12 = Reshape[T=DT_UINT8, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](DecodeRaw_3/_111, Reshape_12/shape)]]
```

**Comment by NoahLu1105** [comment]
change train.py

**Comment by fuchao01** [comment]
@AnberLu  I met, too, how to fix it.

**Comment by NoahLu1105** [comment]
@fuchao01 

1728=24×24×3  ;
6912=48×48×3 ;

so ,

problem is in train.py 
```
 landmark_dir = os.path.join('./Data/imglists/RNet','landmark_landmark.tfrecord_shuffle')
```

**Comment by beibeiaishuijiao** [comment]
@AnberLu, When I run train_RNet.py, I meet the question too. Do you know how to fix it? Is it due to the wrong  RNet data processing?
