### ISSUE TITLE
运行train_pnet

### ISSUE THREAD

**Issue by missyangyangyang** [AITTSMD/MTCNN-Tensorflow#256]
想问一下运行代码时出现如下错误是怎么回事
WARNING:tensorflow:From D:\github\MTCNN-Tensorflow-master\train_models\mtcnn_model.py:239: get_regularization_losses (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.get_regularization_losses instead.
2019-03-20 16:21:42.482675: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "D:/github/MTCNN-Tensorflow-master/train_models/train_PNet.py", line 33, in <module>
    train_PNet(base_dir, prefix, end_epoch, display, lr)
  File "D:/github/MTCNN-Tensorflow-master/train_models/train_PNet.py", line 19, in train_PNet
    train(net_factory,prefix, end_epoch, base_dir, display=display, base_lr=lr)
  File "D:\github\MTCNN-Tensorflow-master\train_models\train.py", line 185, in train
    os.mkdir(logs_dir)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './logs/PNet'
希望能给一些提示，还是个小白有很多不太懂的地方

**Comment by missyangyangyang** [comment]
还是路径的问题，

> 想问一下运行代码时出现如下错误是怎么回事
> WARNING:tensorflow:From D:\github\MTCNN-Tensorflow-master\train_models\mtcnn_model.py:239: get_regularization_losses (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
> Instructions for updating:
> Use tf.losses.get_regularization_losses instead.
> 2019-03-20 16:21:42.482675: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> Traceback (most recent call last):
> File "D:/github/MTCNN-Tensorflow-master/train_models/train_PNet.py", line 33, in 
> train_PNet(base_dir, prefix, end_epoch, display, lr)
> File "D:/github/MTCNN-Tensorflow-master/train_models/train_PNet.py", line 19, in train_PNet
> train(net_factory,prefix, end_epoch, base_dir, display=display, base_lr=lr)
> File "D:\github\MTCNN-Tensorflow-master\train_models\train.py", line 185, in train
> os.mkdir(logs_dir)
> FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './logs/PNet'
> 希望能给一些提示，还是个小白有很多不太懂的地方

还是路径的问题，已经解决了
