### ISSUE TITLE
../../DATA/12 Non existing

### ISSUE THREAD

**Issue by RoboEvangelist** [AITTSMD/MTCNN-Tensorflow#272]
I get this error:

```
:~/MTCNN-Tensorflow$ python prepare_data/gen_12net_data.py
Traceback (most recent call last):
  File "prepare_data/gen_12net_data.py", line 16, in <module>
    os.mkdir(save_dir)
OSError: [Errno 2] No such file or directory: '../../DATA/12'
```

I also get this other error:

```
:~/MTCNN-Tensorflow/prepare_data$ python gen_12net_data.py
Traceback (most recent call last):
  File "gen_12net_data.py", line 7, in <module>
    from prepare_data.utils import IoU
ImportError: No module named prepare_data.utils
```

**Comment by xiaqing10** [comment]
Check the filename .  such as ../../DATA/No_Landmark_12'

**Comment by RoboEvangelist** [comment]
I eliminated the ".." from ../../Data, and now it works.
